// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7wyEuWZEyPJNi0298UZ0EcWx3-4FSLE',
    appId: '1:113161585626:web:4e384fe09b4d71ee0f36e3',
    messagingSenderId: '113161585626',
    projectId: 'smart-greenhouse-system-app',
    authDomain: 'smart-greenhouse-system-app.firebaseapp.com',
    storageBucket: 'smart-greenhouse-system-app.firebasestorage.app',
    measurementId: 'G-KC7JC19XYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPEm-2itm37tlYXPqD92J2-Riaf-Mzits',
    appId: '1:113161585626:android:e5f9cd8ca38a29990f36e3',
    messagingSenderId: '113161585626',
    projectId: 'smart-greenhouse-system-app',
    storageBucket: 'smart-greenhouse-system-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm90uFH0Z0g9IUhh8hPxg64FKUAXKmt4g',
    appId: '1:113161585626:ios:db7ff38159a49fad0f36e3',
    messagingSenderId: '113161585626',
    projectId: 'smart-greenhouse-system-app',
    storageBucket: 'smart-greenhouse-system-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm90uFH0Z0g9IUhh8hPxg64FKUAXKmt4g',
    appId: '1:113161585626:ios:db7ff38159a49fad0f36e3',
    messagingSenderId: '113161585626',
    projectId: 'smart-greenhouse-system-app',
    storageBucket: 'smart-greenhouse-system-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW7wyEuWZEyPJNi0298UZ0EcWx3-4FSLE',
    appId: '1:113161585626:web:959a14fbb3320e720f36e3',
    messagingSenderId: '113161585626',
    projectId: 'smart-greenhouse-system-app',
    authDomain: 'smart-greenhouse-system-app.firebaseapp.com',
    storageBucket: 'smart-greenhouse-system-app.firebasestorage.app',
    measurementId: 'G-L5X06CP46N',
  );

}